### ISSUE TITLE
Getting error 6 when uploading apk of ConfigUpdater (4.4.4-1227136)

### ISSUE THREAD

**Issue by lorn10** [android-police/apkmirror-public#105]
#### Steps to reproduce the problem: Uploading the file in the attachment to APK Mirror. It is the last (and newest version) of ConfigUpdater 4.4.4-1227136 for KitKat.
[com.google.android.configupdater_4.4.4-1227136-19_minAPI19(nodpi).apk.zip](https://github.com/android-police/apkmirror-public/files/3935137/com.google.android.configupdater_4.4.4-1227136-19_minAPI19.nodpi.apk.zip)

**Comment by archon810** [comment]
The issue in this case is the application name field is empty, and we do not accept such APKs as well as APKs with empty version names, which also exist.
