### ISSUE TITLE
Twitter APK blocked at 7/11

### ISSUE THREAD

**Issue by waldner** [android-police/apkmirror-public#106]
The last available version of the twitter app on apkmirror is from 7/11/2019. A recent vulnerability was patched and new versions of the apk have been published.

**Comment by archon810** [comment]
Twitter has switched to dynamic app bundles (split APKs). We will support split APKs in early 2020, and that's when the new versions will start flowing again.

I will close this for now, as it will happen automatically.

**Comment by waldner** [comment]
Has Whatsapp switched as well? Last release on apkmirror is from 14/12. Is there a list of the packages which have switched and will be available again "early 2020"?

**Comment by archon810** [comment]
No, WhatsApp hasn't switched - they just haven't released an update since, probably due to the holiday freeze.

There's no such list available, sorry.

**Comment by waldner** [comment]
Thanks!
