### ISSUE TITLE
Accept compressed files with multiple apps

### ISSUE THREAD

**Issue by NatoBoram** [android-police/apkmirror-public#108]
It would be interesting if it was possible to extract all APKs of a device, compress them in a convenient format, then upload them all at once.

One use case where it would be convenient is when there's a major OS upgrade or a Pixel upgrade, some apps can be installed to gain additional features. If it was possible to upload them all at once, they'd be far more accessible and it would be easier to hunt for them all.

**Comment by archon810** [comment]
This isn't something we'll support. You're welcome to utilize something like ML Manager to multi select apks and upload them in bulk though.
