### ISSUE TITLE
Can't find latest version of Google Photos to download

### ISSUE THREAD

**Issue by eddywitkamp** [android-police/apkmirror-public#110]
#### Expected behavior
Search for Google Photos, click on it from the search results and press the download button to download the latest version.

#### Actual behavior
Search for Google Photos (it appears only on the APPS tab, not in the APKs tab, don't know if this is related), pressing the Info icon it shows: 

Version: 4.42.0.298468093
Uploaded: March 4, 2020 at 9:34PM GMT+0100
File size: 29.11 MB

I press the download icon, scroll down and at the top of the list I can only see:
All versions
Google Photos 4.19.0.254093387
18 variants
October 7

#### Steps to reproduce the problem
see above

On the ALL VARIANTS tab there is no version to be found from 2020 either.

Is this an issue or am I looking in the wrong location to find the latest versions?
The same goes for Google Photos (Daydream), don't know about other apps.

**Comment by archon810** [comment]
Apologies for the confusion - we're currently in soft launch mode for split APKs, which means we're hiding APK bundle results for now, but it looks like you found a bug where the newer split APKs versions are showing to those not in the soft launch.

Here's the ticket tracking split APK support https://github.com/android-police/apkmirror-public/issues/107.

For more information, check here https://www.androidpolice.com/2018/05/30/android-app-bundles-dynamic-delivery-will-change-way-phone-gets-software/.

The launch is near! https://twitter.com/ArtemR/status/1236027260580163585

**Comment by eddywitkamp** [comment]
Ahh I see now how this is related....I would not be able to install a newer version anyway :)
Too bad the latest versions of Facebook and Google Photos are crashing hard on OnePlus6. I'll revert to some older versions. Thanks and good luck with the app and Split APK support!

**Comment by archon810** [comment]
The (i) button bundle version leakage fix has been rolled out.

Hopefully, we won't need it for too long https://twitter.com/ArtemR/status/1237087514411720704.
