### ISSUE TITLE
Misunderstanding of apk targeting at different dpi as same apk

### ISSUE THREAD

**Issue by Kelvin15179** [android-police/apkmirror-public#111]
#### Expected behavior
Uploading the apk with the same version which was previously uploaded but with different target dpi shall be allowed

#### Actual behavior
The system just regarded it as the same apk which has been uploaded before.

#### Steps to reproduce the problem
Uploading the apk with the same version but different dpi as the apk with the same version that the website has received. ie Uploading the apk targeting at 640dpi will be seen same as an apk targeting at 480dpi.

**Comment by archon810** [comment]
Hi @Kelvin15179, I'm not sure I understand - we do not treat APKs with different DPI resources as similar and allow them to be uploaded. Google Play Services is a great example of this.

Can you point to a specific case and perhaps share 2 APKs that can demonstrate the issue?

Thanks.

**Comment by Kelvin15179** [comment]
I have found that the issue being solved suddenly. Well, at the time when Apkmirror had not receive 640dpi varient of version 8.0.07 of app com.sec.android.emergencylauncher , the website had mislabelled the 640dpi varient of the app,which I was uploading at that time, as the apk with only 480dpi support.
