### ISSUE TITLE
Can't make selection from initial menu on Fire TV box

### ISSUE THREAD

**Issue by ryanjjennings** [android-police/apkmirror-public#112]
#### Expected behavior
Move cursor to Browse Files

#### Actual behavior
I don't see any cursor movement

#### Steps to reproduce the problem
Launch AA on a second gen firetv box.

**Comment by archon810** [comment]
Hi,

We haven't tested the app on a Fire device, but on an Nvidia Shield, for example, the right stick controls the cursor movement. Is that not the case on the Fire?

We'll look into supporting Fire devices in the future.

**Comment by ryanjjennings** [comment]
I usually navigate with the phone app.  There is a finger swipe to move the selection cursor around.  That doesn't seem to work though.

**Comment by archon810** [comment]
Another request for this here https://www.androidpolice.com/2020/03/24/apkmirror-installer-for-android-now-in-public-beta-lets-you-install-app-bundles-and-apks/#comment-4846068896.

**Comment by archon810** [comment]
We have added full ATV support, meaning dpad works fully now and is able to navigate all parts of the app. I'll likely release to beta this weekend, and if I'm right, it should fix Fire TV support.

Not sure if Fire TV supports installing split APKs though.

**Comment by archon810** [comment]
I just tested on a real Fire TV, and sadly there are issues, likely due to how old the Android version Fire TV uses is.

Not only does D-pad support not work, even though it does on Android TV, there is a "unable to list files" bug, similar to https://github.com/android-police/apkmirror-public/issues/118.

We'll continue working on this ticket, but no good news today, sorry.

**Comment by archon810** [comment]
Aha! I just opened the app in the Android TV 5.1 emulator, and the same D-Pad issue exists there. So you don't need a Fire TV for this bug.

**Comment by archon810** [comment]
A lead on another Fire OS tester https://twitter.com/MattTommo22122/status/1250943709350432770.

**Comment by archon810** [comment]
Hooray! Fire TV support has arrived with v1.2.2 (13-4).

https://www.apkmirror.com/apk/apkmirror/apkmirror-installer-official/apkmirror-installer-official-1-2-2-13-4-release/

I have a really old Fire TV Stick, so the installation is extremely slow, but it works now.

![IMG_20200418_142553](https://user-images.githubusercontent.com/469543/79671938-bd4ea180-8182-11ea-84d3-690e1697e8dd.jpg)
