### ISSUE TITLE
Fail to upload Facebook Lite Beta

### ISSUE THREAD

**Issue by EMK2000** [android-police/apkmirror-public#115]
The latest Facebook Lite Beta seems changed to APK Bundle. 

I tried upload through both ML Manager and APKMirror Web. Both failed. 

Error message: 
APK is a configuration split, but we need the base APK first. 

All APKs:
base.apk
split_fizz.apk
split_java.com.facebook.lite.inappbrowser.apk
split_java.com.facebook.video.heroplayer.service.apk

Only the first one can be uploaded, and all three other are failed.

**Comment by archon810** [comment]
This happens to very few apps, we also side with Instagram. The reason is this base.apk doesn't have anything to do with configuration splits and is not marked as a base APK in its manifest. The only splits available are feature splits, which are not required for the app to run.

**Comment by archon810** [comment]
This was fixed a few months ago.
