### ISSUE TITLE
APKMirror Installer: Annual subscription issue

### ISSUE THREAD

**Issue by nameloc2080** [android-police/apkmirror-public#117]
Subscriptions don't seem to offer 2 full months free at UK GBP annual pricing, although level 2 is very close. Ver 1.1.1 (6-3). 
![1](https://user-images.githubusercontent.com/19313473/77530506-5abafc00-6e89-11ea-95c8-a7897ca03ccf.png)
![2](https://user-images.githubusercontent.com/19313473/77530508-5b539280-6e89-11ea-8de6-97abaaf1864a.png)

**Comment by archon810** [comment]
We only set the pricing in the US (to $1.99 and $19.99), and the Play Store converts it to other currencies. Not sure why they'd be off by that much, but it'd be unreasonable for us to set exact amounts in every currency.

**Comment by nameloc2080** [comment]
I'm just nitpicking but its a shame the play store can't handle this in a consistent way. The level 2 annual rate in GBP is nearly spot on. Thanks for feeding back on this.

**Comment by archon810** [comment]
¯\_(ツ)_/¯

I also realize that $1.99 x 10 is $19.90 and not $19.99 which is technically adding a little to the difference here, but it shouldn't be that much.
