### ISSUE TITLE
Media Database is very large

### ISSUE THREAD

**Issue by zin07** [android-police/apkmirror-public#122]
#### Expected behavior
When adding a new music album to the library VLC should create a database file that is small.

#### Actual behavior
Upon adding a new audio album to the library the associated database is very large, from 4 to 10 mb per album!! I have 144 albums and the userdata is 498mb!

#### Steps to reproduce the problem
Add a new music album that has album art and is tagged to library (mine areflac files). Go to the VLC application storage and note that user data has gone up by several mb!

**Comment by archon810** [comment]
This is not a place to report VLC issues.
