### ISSUE TITLE
Failed to upload apk

### ISSUE THREAD

**Issue by kirilkirov01** [android-police/apkmirror-public#125]
#### Expected behavior
To work without a problem

#### Actual behavior
Gives error every time I upload my apk

#### Steps to reproduce the problem
I write my name, enter my email and when I add the apk and start uploading it tells me "No thanks." 
![Screenshot_20200416-114159_Chrome](https://user-images.githubusercontent.com/59082370/79434610-4cb75180-7fd7-11ea-93b1-6e4087e6e027.jpg)

**Comment by archon810** [comment]
What app is this?

**Comment by kirilkirov01** [comment]
I build the app and would like to share it only with friends. It's not
virus it's not some kind of scam or something like this, it's just our
website for our Arduino weather stations converted to apk.

**Comment by archon810** [comment]
Sorry, APKMirror is highly curated, and this is not the kind of app we'd accept.
