### ISSUE TITLE
Not working on huawei p8lite

### ISSUE THREAD

**Issue by TheW0LVERIN3** [android-police/apkmirror-public#126]
#### Expected behavior
It is supposed to install the apkm

#### Actual behavior
It always gives me this issue.(see picture)
![Screenshot_2020-04-18-01-14-43](https://user-images.githubusercontent.com/44342613/79621212-d3247e00-8112-11ea-8db1-b362fa17988f.png)

Nothing I can find fixes it. Android 6.0 on huawei p8lite (emui 4.0.3). It does work with normal apk files. It gives the same error on my other phone: huawei y6 android 5.1.1(emui 3.1).

#### Steps to reproduce the problem
Trying to install any apkm file.

**Comment by archon810** [comment]
Unable to list file is a known issue on older/slower devices. The next update should fix it.

However, I am not sure all Huawei devices will be able to work for a different reason, though disabling MIUI optimizations makes it work for many.

See #116.

**Comment by TheW0LVERIN3** [comment]
As far as I know the only thing I can disable is battery optimisations and that doesn't work

**Comment by archon810** [comment]
I just pushed out a fix, can you please see if it works for you now?

https://www.apkmirror.com/apk/apkmirror/apkmirror-installer-official/apkmirror-installer-official-1-2-1-12-4-release/

> What's new in 1.2.1 (12-4):
> - Fixed D-pad not working on older versions of Android TV and Fire TV
> - Fixed "Unable to list files" errors that sometimes popped up on older and slower hardware

**Comment by TheW0LVERIN3** [comment]
It is now doing this. It was working until it tries to install after which it waits for a little while and then spews out this error.
![Screenshot_2020-04-18-02-54-33](https://user-images.githubusercontent.com/44342613/79624114-f99ce600-811f-11ea-8f76-d0ddf1197047.png)

**Comment by archon810** [comment]
I actually just ran into the same issue myself on an older emulator. One down, one or two more to go!

Android development is hard, man.

**Comment by TheW0LVERIN3** [comment]
Good luck and thank you. Cant'wait.

**Comment by archon810** [comment]
Alright, let's try this https://www.apkmirror.com/apk/apkmirror/apkmirror-installer-official/apkmirror-installer-official-1-2-2-13-4-release/.

> What's new in 1.2.2 (13-4):
> - Fixed D-pad not working on older versions of Android TV and Fire TV
> - Fixed "Unable to list files" and "Parser was given a path that is not a file or does not end with the expected '.apk' extension" errors that sometimes popped up on older and slower hardware

**Comment by TheW0LVERIN3** [comment]
It now works perfectly, thx. Although the open app button after installation does not work. Also how do you switch to internal storage if you have the external set as standard in the app?

**Comment by archon810** [comment]
@TheW0LVERIN3 Has the Open button not been working for you ever since? I've never seen a case where it doesn't work, so this is weird.

Regarding external storage support, we're hoping to add it soon.

**Comment by TheW0LVERIN3** [comment]
It works now. I think it must have gotten fixed in some of the last updates. Thx again.
