### ISSUE TITLE
Bug by design: on R, if you grant the app install-permission, it will be forced-stopped

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android-police/apkmirror-public#132]
Please consider checking it out:
https://www.reddit.com/r/androiddev/comments/gvhwzd/android_r_app_granted_install_permission_and_got/

https://issuetracker.google.com/issues/158018379

It will affect this app too.

**Comment by archon810** [comment]
Sigh, what is Google doing... our app gets killed too, makes no damn sense.

**Comment by archon810** [comment]
I'll close it since there's nothing we can do but ask Google why this is done and keep the pressure on.

**Comment by AndroidDeveloperLB** [comment]
@archon810 Sorry for that. Just didn't know where to write you. Tried to contact Android Police too. I hope they will consider writing about it.
Maybe with some people starring those, Google will reconsider.
Google already made some terrible choices on Android over the past years. 

In the past, I was excited for each new version : What will they bring next.
Nowadays, it's the opposite: What will they ruin next...

**Comment by archon810** [comment]
Our coverage: https://www.androidpolice.com/2020/06/03/android-11-install-unknown-apps-more-cumbersome/.

**Comment by AndroidDeveloperLB** [comment]
@archon810 Sadly you didn't put a link to what I've put (of reddit). Can you please consider it?
Maybe it will encourage more people to write about it.

**Comment by archon810** [comment]
I've added it.

**Comment by AndroidDeveloperLB** [comment]
Nice. Thank you. Do you think Google will fix this issue, or at least admit that it's an issue?

**Comment by archon810** [comment]
No idea. I know they've heard us, so we'll have to leave it to them to discuss and hopefully come up with a workaround.

**Comment by AndroidDeveloperLB** [comment]
I hope they will also fix this issue related to installing, that I've reported :
https://issuetracker.google.com/issues/154212612

It occurs on all installers that I've found so far.
The installer app can't know what's going on, so it thinks it's still in progress.

**Comment by archon810** [comment]
Starred, thanks. We also ran into this issue but I never bothered to file a bug.

**Comment by AndroidDeveloperLB** [comment]
Your miss. I got more star points there. :)

I've tried to find how to detect it too, but I failed. If you know of a workaround please let me know (maybe better to write there though)
