### ISSUE TITLE
pokemon go 0.175.1-0.179.0 won't install on my Android 5 32-bit mobile

### ISSUE THREAD

**Issue by tyu366** [android-police/apkmirror-public#135]
#### Expected behavior
apkm installed on demand

#### Actual behavior
the app keeps prompting 'you have to select at least one architecture split file' but nothing can be selected on the app.  Not sure it is due to dpi issue.  The app says my dpi is 480 but app says split_config.xxxhdpi.apk (640 - xxx hdpi).  Fortunately, I have found another source (normal apk) a few days later and the app runs smoothly.

#### Steps to reproduce the problem
run the installer
select the apkm file
click the button to install the app

**Comment by archon810** [comment]
What's your device? Can we see a screenshot?

I'm fairly sure I know what this is though, and we'll have a fix out shortly.

Additionally, we've also had regular APKs for Pokémon Go for a few releases now. You don't have to go looking elsewhere!

**Comment by tyu366** [comment]
I encounter the issue since 0.175.  I have seen the apk 0.179.0 uploaded
for A few day but play store remains unavailable.  I have tried your
installer but the same issue remains.  Luckily I have found A regularvapk
to install.

model asus zenfone 2 ze551ml 4+64GB running android 5.0

Artem Russakovskii <notifications@github.com> 于 2020年6月23日周二 23:04写道：

**Comment by archon810** [comment]
OK, the Zenfone 2 issue is known. A fix will be out soon. 

Regular APKs are available for Pokemon Go 0.179.0 and have been for a few days btw https://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-179-0-release/.

**Comment by archon810** [comment]
This issue should be fixed in v1.3+.
