### ISSUE TITLE
inoreader is blocked?

### ISSUE THREAD

**Issue by patrickdrd** [android-police/apkmirror-public#137]
apkmirror feeds produced errors in inoreader so I emailed them and I received the following response from them:

> It looks like their Cloudflare protection is causing this. Are you able to contact them and ask about that?
> If you/they need any further info such as IP address pools and useragent, we'll be glad to assist.

> Please turn JavaScript on and reload the page.Checking your browser before accessing apkmirror.com.Please enable Cookies and reload the page.This process is automatic. Your browser will redirect to your requested content shortly.Please allow up to 5 seconds…+((!+[]+(!![])+!![]+!![]+!![]+!![]+!![]+!![]+[])+(!+[]+(!![])+!![])+(!+[]+(!![])+!![]+!![]+!![]+!![]+!![]+!![])+(!+[]-(!![]))+(!+[]+(!![])+!![]+!![])+(+!![])+(!+[]+(!!))DDoS protection by Cloudflare
> --
> 
> 
> 

sample feed:
https://www.apkmirror.com/apk/arlosoft/macrodroid-device-automation-2/feed/

I guess feed readers should be excluded from cloudflare protection mechanisms?

**Comment by archon810** [comment]
I recently blocked Choopa (a hosting company) bots for abuse, and Inoreader from what I can tell is running from A1 Bulgaria primarily. However, they also have 2 IPs hitting us from Choopa. Can you ask them why that is? Is it a backup only, because A1 Bulgaria requests are still coming through fine.

**Comment by patrickdrd** [comment]
yes, sure, I've already sent your post to them

**Comment by archon810** [comment]
In the meantime, I made some changes to our firewall config, so please reopen this if you still continue to see the issue.
