### ISSUE TITLE
Server Error 504 (Gateway Timeout)

### ISSUE THREAD

**Issue by SScylla** [android-police/apkmirror-public#138]
#### Expected behavior
Clicked on "download", expected to get transferred to download page / get a automatic download process going

#### Actual behavior
exorbitant loading times, resulting in "Error 504"

#### Steps to reproduce the problem
for me, click on any download, it will come, eventially.

Cloudflare Ray ID: 5ba0a534ba679710

**Comment by archon810** [comment]
Thanks for your report. We're currently experiencing an outage and are working with our host to mitigate it. I hope we'll be back soon.
