### ISSUE TITLE
Change showed GMS variant number on versions list page

### ISSUE THREAD

**Issue by Displax** [android-police/apkmirror-public#139]
#### Actual behavior
Currently it showing build number of each variant, like this:
![false](https://user-images.githubusercontent.com/16293419/89102142-fbf52880-d40e-11ea-9cb2-fdc2dbbd3f5e.PNG)

#### Expected behavior
But it need to showing six-digit number in version  "20.24.14 (**XXYYZZ**-319035315)", like this:
![true](https://user-images.githubusercontent.com/16293419/89102190-66a66400-d40f-11ea-8716-d0248a44ef7e.PNG)

On [all variants tab](https://www.apkmirror.com/apk/google-inc/google-play-services/#variants) all variants shows correctly.

**Comment by archon810** [comment]
The issue is now resolved.

For example: https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-20-50-66-release/

![image](https://user-images.githubusercontent.com/469543/109212361-469c1080-7764-11eb-925f-4fc4d460ec0a.png)
