### ISSUE TITLE
Download buttons missing

### ISSUE THREAD

**Issue by cafevincent** [android-police/apkmirror-public#140]
#### Expected behavior
Out of all the apk download sites yours is the only one without a download button for files. WTF?

#### Actual behavior
no download button, as seen (for example) here
https://www.apkmirror.com/apk/private-internet-access/vpn-by-private-internet-access/vpn-by-private-internet-access-3-7-1-release/
I tried it in mobile browser and desktop firefox/waterfox, can't find it

#### Steps to reproduce the problem
just load the page

btw I find it just plain wrong that you have to create a github account just to send you a simple feedback.

**Comment by SeBsZ** [comment]
On the page you linked, you have to click on the variant you want to get to the download page:
![image](https://user-images.githubusercontent.com/5457531/89633277-e1ee9680-d8a3-11ea-8fb9-bf8e8684b1fb.png)

If you did not want to create a Github account, you could also use our contact form: https://www.apkmirror.com/contact-us/

Please let us know if you have any more questions.
