### ISSUE TITLE
App is not available for Nvidia Shield

### ISSUE THREAD

**Issue by ZakTaccardi** [android-police/apkmirror-public#141]
Using an Nvidia shield 2015 and I'm unable to install this app directly from the play store (it's available for my phone, but not my Nvidia shields).

I imagine I could sideload it, but would prefer to install it from the play store directly if possible

**Comment by apksupport** [comment]
go to apk.support and select your device

**Comment by archon810** [comment]
We have a few tasks that the ATV team told us we need to implement before they can approve ATV compatibility. Hopefully, we'll be able to accomplish that in the next few weeks.

We do understand 2 out of 3, but the 3rd one - d-pad support - is already implemented, and yet they continue to insist it's not. Hopefully, they'll be able to clarify this one.

**Comment by ZakTaccardi** [comment]
I didn't realize that Android TV apps need to be specially approved. This probably explains a lot.

Thanks!

**Comment by samethernet** [comment]
> 
> 
> I didn't realize that Android TV apps need to be specially approved. This probably explains a lot.
> 
> Thanks!

I believe this approval process is a way to minimize the amount of badly written apps for the Android TV platform. I too am waiting for the Android TV Version to be able to test how well it works.

**Comment by archon810** [comment]
And we're live! https://play.google.com/store/apps/details?id=com.apkmirror.helper.prod

https://twitter.com/ArtemR/status/1301300444677898241

![Google Play Store_20200902_160938](https://user-images.githubusercontent.com/469543/92047166-4c76e300-ed39-11ea-80a7-345f305e312e.png)
![Google Play Store_20200902_160856](https://user-images.githubusercontent.com/469543/92047168-4da81000-ed39-11ea-938b-624d10b02441.png)
