### ISSUE TITLE
error while reading apk file data with iceweasle fenix fork

### ISSUE THREAD

**Issue by TheW0LVERIN3** [android-police/apkmirror-public#142]
#### Expected behavior
It should just install the apk: https://github.com/interfect/fenix/releases

#### Actual behavior
It gives an error: eror ocurred while reading apk file data. Installing the apk without the app does work, so it is a problem with the app.

#### Steps to reproduce the problem
Try installing the apk linked above with the apkmirror app. I am running the latest play store version.
![Screenshot_20200811-132108](https://user-images.githubusercontent.com/44342613/89891931-33659100-dbd6-11ea-9f42-e2279e34e1dd.png)

**Comment by TheW0LVERIN3** [comment]
I gave a samsung a5 2016 european version running android 7.

**Comment by archon810** [comment]
@interfect The reason this is happening is because android:versionName is blank. Is there a reason it's not being set in these builds?

**Comment by interfect** [comment]
It's because I didn't know I had to do anything to set it. Apparently with the build system I'm using it needs to be done manually.

I can set it for the next release.
