### ISSUE TITLE
Why is the app not open source?

### ISSUE THREAD

**Issue by deltabravozulu** [android-police/apkmirror-public#143]
#### Expected behavior
Github has source code. 

#### Actual behavior
Github doesn't have source code.

#### Steps to reproduce the problem
Go to https://github.com/android-police/apkmirror-public

#### Commentary
I understand that this is a general repo for apkmirror.com, but the new apkm processor has a link to here. It would be good to open source it. Even the [unofficial app](https://forum.xda-developers.com/showpost.php?p=68428799)  has [source code](https://github.com/vojta-horanek/APKMirror)

**Comment by archon810** [comment]
The app is ad-supported, and a community edition is not planned at this time.
