### ISSUE TITLE
My app doesn't upload

### ISSUE THREAD

**Issue by TheAlienDrew** [android-police/apkmirror-public#146]
#### Expected behavior
Upload the app.

#### Actual behavior
Says "No thanks."

#### Steps to reproduce the problem
Upload my app to the store to see for yourselves. At the moment it is located on the Play Store, Amazon appstore, Aptoide, and XDA Labs. It is called Unofficial Sticky Notes.

https://play.google.com/store/apps/details?id=aliendrew.ms.stickynotes

https://www.amazon.com/dp/B07XLK8KVC/ref=apps_sf_sta

https://aliendrew-stickynotes.en.aptoide.com/?store_name=aliendrew&app_id=53111131

https://labs.xda-developers.com/store/app/aliendrew.ms.stickynotes

**Comment by archon810** [comment]
Hi,

I decided to approve this app now that it's had some time to bake. https://www.apkmirror.com/apk/aliendrew/unofficial-sticky-notes/unofficial-sticky-notes-2-8-4-release/
