### ISSUE TITLE
Breadcrumbs not aligned properly on Peacock TV – Stream TV, Movies, Live Sports & More (Android TV) page

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#147]
#### Expected behavior
It should be aligned properly... 

#### Actual behavior
![Screenshot_20200904-173239_Chrome](https://user-images.githubusercontent.com/67194650/92237503-1a01ed00-eed5-11ea-8e6c-bd00a97c0f81.png)

#### Steps to reproduce the problem
Visit https://www.apkmirror.com/apk/peacock-tv-llc/peacock-tv-android-tv/peacock-tv-android-tv-1-2-12-peacocktvgoogle-release/peacock-tv-stream-tv-movies-live-sports-more-android-tv-1-2-12-peacocktvgoogle-android-apk-download/

**Comment by archon810** [comment]
This bug is now fixed, thanks for reporting.
