### ISSUE TITLE
Wrong developer name for JioCall app

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#149]
#### Expected behavior
Developer name: 
Jio Platforms Limited
#### Actual behavior
Developer name:
Reliance Corporate IT Park Limited

#### Steps to reproduce the problem
Visit https://www.apkmirror.com/apk/reliance-corporate-it-park-limited/jio4gvoice/

**Comment by archon810** [comment]
Fixed, thanks.
