### ISSUE TITLE
Some apps of Reliance Corporate IT Park Limited now belong to Jio Platforms Limited

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#150]
#### Expected behavior
Some apps of Reliance Corporate IT Park Limited should be moved to Jio Platforms Limited
For example,
Jio Browser
https://www.apkmirror.com/apk/reliance-corporate-it-park-limited/jiobrowser-fast-lite-indian-language-support/

#### Actual behavior
Some apps of Jio Platforms Limited are still listed under Reliance Corporate IT Park Limited

#### Steps to reproduce the problem
Visit https://www.apkmirror.com/apk/reliance-corporate-it-park-limited/jiobrowser-fast-lite-indian-language-support/ and
Visit https://play.google.com/store/apps/details?id=com.jio.web

**Comment by archon810** [comment]
This was the only app. Moved, thanks.
