### ISSUE TITLE
Wrong developer name for Mint Keyboard app

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#151]
#### Expected behavior
Mint Keyboard by By Xiaomi Inc.

#### Actual behavior
Mint Keyboard by Bobble AI Technologies

#### Steps to reproduce the problem
```
Visit https://www.apkmirror.com/apk/xiaomi-inc/mint-keyboard-stickers-gif-font-themes/ and
https://play.google.com/store/apps/details?id=com.mint.keyboard
```

**Comment by archon810** [comment]
Fixed, looks like they migrated devs, and Bobble AI Technologies is a technology partner.
