### ISSUE TITLE
The samsung electronics s page will not load

### ISSUE THREAD

**Issue by coltrain11** [android-police/apkmirror-public#153]
#### Expected behavior
S page won't load at all

#### Actual behavior
S page won't load 

#### Steps to reproduce the problem
https://www.apkmirror.com/apk/samsung-electronics-co-ltd/page/19/

**Comment by archon810** [comment]
Thank you for the report. We have redone how splitting up by first letter and pagination are done, and now the issue is fixed.

Letter S is loading great and has a lot of pages! https://www.apkmirror.com/apk/samsung-electronics-co-ltd/S/
