### ISSUE TITLE
On Hisense 43H6570G tv when loading .apkm files in apkmirror installer the tv restarts.

### ISSUE THREAD

**Issue by joejoejo** [android-police/apkmirror-public#154]
Expected behavior
APKMirror Installer should allows you to install .apkm files

Actual behavior
when loading a .apkm file to the apkmirror file l,oaded page on my tv via the APKMirror Installer app it just restarts the tv and not to the file loaded page

Steps to reproduce the problem
open APKMirror Installer
open to the folder where the .apkm file is located
then click the .apkm file
click on install package
then the tv will restart
or open a file manager
go to the folder where the .apkm file is located
have the file manager app open the file with APKMirror Installer.
it will not even open APKMirror Installer, could display a white screen when trying to open APKMirror Installer and the .apkm file
then the tv will restart

**Comment by archon810** [comment]
I'm sorry, I don't have such a TV to test on, and if a TV restarts, the bug is likely in the TV firmware as no app should be able to crash the whole TV / OS. Afraid we aren't able to help.
