### ISSUE TITLE
RSS feed is getting blocked by cloudflare which makes no sense

### ISSUE THREAD

**Issue by GoRhY** [android-police/apkmirror-public#155]
#### Expected behavior

I want to do a simple PHP script to read 2 feeds

#### Actual behavior

Request are being blocked by cloudflare. This has no sense as feeds are made to be read.

#### Steps to reproduce the problem

Any simple curl petition (or file_get_contents) to any feed URL will give an error

![image](https://user-images.githubusercontent.com/7281306/97754692-406c8f00-1af8-11eb-9606-44e9f977c398.png)

**Comment by archon810** [comment]
APK Mirror places challenges on a variety of cloud hosting platforms which are ripe with bots and hackers. You may be using such a platform, and this is why you're seeing this captcha.
