### ISSUE TITLE
REPS Heart Rate Monitor older versions

### ISSUE THREAD

**Issue by QuickKnight106** [android-police/apkmirror-public#156]
I have tried to download the Heart Rate Monitor version 4.4 and it won't start the download. I then tried to download the 4.5 version, but that won't work either. The status bar keeps flashing as though waiting for the download to start...but that's all that happens.

I am running Android 7, so the most recent version won't work properly on my tablet (Nexus 9), therefore I need an older version.

Can you help please?

**Comment by archon810** [comment]
I was able to download properly, for example from https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=1573196.

![image](https://user-images.githubusercontent.com/469543/98308573-3bd32b00-1f7d-11eb-9247-5c34ff5c994c.png)
