### ISSUE TITLE
Upload not come live in the apkmirror

### ISSUE THREAD

**Issue by lawalfataikola123** [android-police/apkmirror-public#161]
#### Expected behavior
I upload my application on apkmirror and is not come live in the store

#### Actual behavior
What happened

#### Steps to reproduce the problem
What can I _do****_

**Comment by TPS** [comment]
IIUC, minimally, if your app isn't published on a major app store 1st, mostly Google Play, your app _won't_ be accepted @ APKMirror.

**Comment by archon810** [comment]
I don't know what app is being talked about.
