### ISSUE TITLE
QR-Code generation not working

### ISSUE THREAD

**Issue by Brawl345** [android-police/apkmirror-public#169]
#### Expected behavior
Creating QR-Code should work

#### Actual behavior
It uh does not

#### Steps to reproduce the problem
1. Go to any page where you can create a QR code (I used https://www.apkmirror.com/apk/world-health-organisation/who-covid-19/who-covid-19-1-0-0-release/ )
2. Click the QR button
3. No QR code shown

It uses the qrserver.com API, which is down (Seems to be longer, I noticed a few other sites). Maybe use a lib that doesn't depend on an API?

**Comment by archon810** [comment]
Working for me...

![image](https://user-images.githubusercontent.com/469543/103105294-b1549280-45e1-11eb-8334-05c3f73a14da.png)

qrserver.com is up for me as well.

**Comment by archon810** [comment]
The issue could be on your end with DNS, perhaps?

**Comment by Brawl345** [comment]
Holy shit you are right, I'm so sorry! It was my DNS block rules, I use the EnergizedProtection blocklist and for some reason it contains this domain. At least now I know what's up, thanks for the tip ;)
