### ISSUE TITLE
Facebook apkm installation failed

### ISSUE THREAD

**Issue by wilsonjor** [android-police/apkmirror-public#170]
#### Expected behavior
Install Facebook app

#### Actual behavior
Error message: App installation failed. Unable to list inside .APKM bundle.

#### Steps to reproduce the problem
Install Facebook 300.2.0.58.129 (arm64-v8a) (360-480dpi) (Android 10+).
com.facebook.katana_300.2.0.58.129-265245035_13feat_a521e26935f58f4ebc1ba896a62e21e7_apkmirror.com.apkm

**Comment by wilsonjor** [comment]
Huawei EMUI 10 (Android 10)

**Comment by archon810** [comment]
What's your version of APKMirror Installer?

**Comment by archon810** [comment]
I'm unable to reproduce this with Installer 1.3.2.
