### ISSUE TITLE
Advanced search - WhatsApp for android 4.0.3 - is not showing valid APK in list

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#175]
#### Expected behavior
It should show Android 4.0.3 APK
e.g. WhatsApp Messenger 2.21.4.21
Includes Android 4.0.3 variant

#### Actual behavior
Shows Android 4.1+ APKs
e.g. WhatsApp Messenger 2.21.6.12 beta
All variants require Android 4.1+

#### Steps to reproduce the problem
Visit https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=whatsapp&minapi=15

**Comment by archon810** [comment]
We're still working on tweaking the minapi search and will roll out an update shortly, but in this particular case I don't see a problem.

https://www.apkmirror.com/?post_type=app_release&searchtype=apk&page=5&s=whatsapp&minapi=15
![image](https://user-images.githubusercontent.com/469543/112050212-d176ed80-8b0d-11eb-84b9-49a9080b3215.png)

**Comment by archon810** [comment]
And if you meant that 4.1+ APKs shouldn't be shown at all, that's exactly what we're hoping to address with the next update. The difference between searching for APKs that are compatible with 4.0.3+ (which includes 4.1+ and everything >= 4.0.3) vs those that have to be compatible with 4.0.3 (<= 4.0.3).
