### ISSUE TITLE
The site does not work in the browser

### ISSUE THREAD

**Issue by Vetal0821** [android-police/apkmirror-public#177]
#### Expected behavior
The user must be able to go to the site: https://www.apkmirror.com/ from the browser **"waterfox classic"** and see all the content of the site 

#### Actual behavior
When opening the site from the browser **"waterfox classic"**, we see the following:  

_Checking your browser before accessing apkmirror.com.
Please enable Cookies and reload the page.
This process is automatic. Your browser will redirect to your requested content shortly.
Please allow up to 5 seconds…_

!!!!Nothing happens after this message !!!

#### Steps to reproduce the problem
- download the browser https://www.waterfox.net/download/
- install on your computer
- go on the website https://www.apkmirror.com/

**Comment by archon810** [comment]
Both I (US) and one of my developers from Poland tested the Classic version, and it does redirect for both of us after passing the check. Can you try again? It could have been an issue with Cloudflare, or something on your end.

**Comment by Vetal0821** [comment]
I try on two PCs, one does not work on the second. I tried to clean the cache, I also used a proxy.
