### ISSUE TITLE
Contains dangerous apps? 

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#183]
#### Expected behavior
APKMirror must not contain dangerous apps

#### Actual behavior
APKMirror contains dangerous apps (as reported by Chrome browser on Android device)
![Screenshot_20210630-201859_Chrome](https://user-images.githubusercontent.com/67194650/123982787-f28a8c80-d9e0-11eb-9a2a-ec59c2830e02.png)

#### Steps to reproduce the problem
Visit
https://www.apkmirror.com/apk/hola/hola-free-vpn-proxy/hola-free-vpn-proxy-1-184-486-release/hola-free-vpn-proxy-unblocker-arm7a_1-184-486-android-apk-download/

**Comment by archon810** [comment]
Google has flagged Hola VPN for some reason, but it's not clear why. Their app is missing from the Play Store now too.

There's http://adios-hola.org/ but it's from 2015.

If you're aware of something that definitively shows Hola isn't safe, we'll consider further action.

**Comment by archon810** [comment]
Google's own page for this https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.apkmirror.com%2Fapk%2Fhola%2Fhola-free-vpn-proxy%2Fhola-free-vpn-proxy-1-184-486-release%2F&hl=en-US simply states "Distribute uncommon downloads" without further explanation, which is nonsense.

**Comment by TPS** [comment]
There're more pertinent details w/ links @ [Wikipedia](https://en.m.wikipedia.org/wiki/Hola_(VPN)#History), starting from the 2015 paragraph onwards.

**Comment by archon810** [comment]
There are some explanations of how their network works, but it doesn't mean it's currently considered malware.

**Comment by andyg21** [comment]
https://www.haaretz.com/israel-news/tech-news/.premium-a-brothers-feud-and-a-trojan-horse-dispute-reveals-web-s-dark-side-1.9959383

**Comment by archon810** [comment]
@andyg21 I'm not a subscriber. Can you share the full text somewhere please?

**Comment by TPS** [comment]
All that's pretty extraordinary.
@archon810 Does it influence this issue 1 way or the other?

**Comment by archon810** [comment]
At this point I don't see a reason to remove Hola from the site unless a more damning and conclusive report comes out, preferably by a security vendor or Google itself. Users will continue to see the notice but only on Hola pages from what I can tell.
