### ISSUE TITLE
 I can not upload my APK through ML Manager

### ISSUE THREAD

**Issue by wooplus123** [android-police/apkmirror-public#190]
Hi, 

I read a guide on APKMirror website. It recommended using ML Manager extractor to upload my APK. But I failed to upload through ML Manager. I am wondering whether should I install ML Manager on my phone to extract my APK? I did all processes through Mac but not work. I don't know how to make it. 

Can you help me? Thanks

**Comment by archon810** [comment]
Can you please describe what doesn't work exactly? What app are you trying to upload and what is the error?

**Comment by wooplus123** [comment]
I want to upload my app (a dating app) on APKMirror, but I was told if I
want to upload my APK on the website, I should make it through ML Manager.
But I found ML Manager is another app? I tried to install it and make an
upload, but have been told "This Google account is not yet associated with
a device. Please access the Play Store app on your device before installing
apps." So that's mean I should install ML Manager on my phone, then I can
upload my APK?

I am so puzzled. I am using Mac to upload, need I change the device? Or can
you tell me how to upload APK on the APKMirror website?

Thanks

Artem Russakovskii ***@***.***> 于2021年9月10日周五 上午11:04写道：

**Comment by archon810** [comment]
What is the Play Store of the dating app exactly?

**Comment by wooplus123** [comment]
I am not sure. Maybe Google Play Store? Or can you just tell me the process
of uploading APK on APKMirror?

Artem Russakovskii ***@***.***> 于2021年9月10日周五 上午11:39写道：

**Comment by archon810** [comment]
Install ML Manager on your phone. Then upload any installed app from there.

What is the dating app? Can you name it and link to it?

**Comment by wooplus123** [comment]
WooPlus. It doesn't install on APPMirror, I don't know how to link it.

Artem Russakovskii ***@***.***> 于2021年9月10日周五 上午11:50写道：

**Comment by archon810** [comment]
You can now find the app here https://www.apkmirror.com/apk/wooplus-dating-for-curvy-people/dating-app-for-curvy-wooplus/dating-app-for-curvy-wooplus-6-2-10-release/.
