### ISSUE TITLE
Sony Email IMAP not syncing

### ISSUE THREAD

**Issue by KMBahamas** [android-police/apkmirror-public#191]
#### Expected behavior
Deleted emails should sync across all platforms (Outlook 2016).  Android to Outlook and Outlook to Android. Using Sony Xperia 10iii,

#### Actual behavior
Deletions not syncing from Android to Outlook, but deletions in Outlook sync to Android.

#### Steps to reproduce the problem
Removed and reinstalled account
Tried email account via Gmail app (it works)
Unistalled and reinstalled app, and email accounts 
Other IMAP accounts (Gmail and Go Daddy) work on email app

**Comment by archon810** [comment]
I'm sorry, but this issue tracker is only for website bugs, not for issues with individual applications.
