### ISSUE TITLE
Beta or Stable - Google Play Services

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#192]
#### Expected behavior
Not sure

#### Actual behavior
Phone version of google play services is marked as "stable" but for android tv, it is marked as "beta".
Google Play services 21.36.14 (Stable)
https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-21-36-14-release/
![image](https://user-images.githubusercontent.com/67194650/134762369-c24735f3-62ef-40bd-a4f9-e0d04cd13218.png)

Google Play services (Android TV) 21.36.14 beta
https://www.apkmirror.com/apk/google-inc/google-play-services-android-tv/google-play-services-android-tv-21-36-14-release/
![image](https://user-images.githubusercontent.com/67194650/134762380-99a7fb2f-d5eb-4587-aae2-92cf3bde7121.png)

#### Steps to reproduce the problem
Visit given links.

**Comment by archon810** [comment]
Fixed, thanks.
