### ISSUE TITLE
Cannot see the list of latest uploaded OPPO APKs

### ISSUE THREAD

**Issue by OneNormalUsername** [android-police/apkmirror-public#193]
#### Steps to reproduce the problem

* Go to https://www.apkmirror.com/apk/oppo/
* Scroll down the page and click on "See more uploads", which redirects you to https://www.apkmirror.com/uploads/?q=oppo

https://user-images.githubusercontent.com/42769194/140837131-9da1d7d7-ec21-4e3c-80df-434abeeb06c5.mp4

#### Actual behavior

APK Mirror displays "No uploads found"

#### Expected behavior

You should be able to see the list of latest uploaded OPPO APKs

**Comment by archon810** [comment]
Thank you, reproduced. We'll fix it ASAP.

**Comment by archon810** [comment]
The underlying cause is there is an app called OPPO+ and a dev called OPPO, both with the same "oppo" slug, so we have a collision because apparently the "more" page doesn't differentiate between apps and devs. Fix incoming soon.

**Comment by archon810** [comment]
The fix has been released.
