### ISSUE TITLE
Files by Google 1.0.406457656 certificate SHA-256 inconsistence

### ISSUE THREAD

**Issue by tienquanutc** [android-police/apkmirror-public#194]
I found there are 2 versions with different SHA256 certificate:  
[files-by-google-1-0-406457656-android-apk-download](https://www.apkmirror.com/apk/google-inc/files-go/files-go-1-0-406457656-release/files-by-google-1-0-406457656-android-apk-download/#safeDownload): 207af9a133a630c4246a06c79c09946a70840f4702ee5baa53f3791b537b0f14    
[files-by-google-1-0-406457656-2-android-apk-download](https://www.apkmirror.com/apk/google-inc/files-go/files-go-1-0-406457656-release/files-by-google-1-0-406457656-2-android-apk-download/#safeDownload): 1c817cae3628ed5726f8020b71483511036213691f7c615c6f974a70a15674f3      
Looks like the version with the hash ending in 4f3 is not valid.

**Comment by archon810** [comment]
Google indeed distributes this app with 2 signatures for whatever reason. eeb3b8455ed4fe64c03039ef005c85b53bdc1d80 first showed up in the Android 12 betas for Pixels.
