### ISSUE TITLE
Broken link on privacy policy page

### ISSUE THREAD

**Issue by andyg21** [android-police/apkmirror-public#197]
#### Expected behavior
Should be valid link
#### Actual behavior
404 - Not found

#### Steps to reproduce the problem
1) Visit privacy policy page:
https://www.apkmirror.com/apkmirror-com-privacy-policy/
2) In Third party advertising section, click "[here](http://www.networkadvertising.org/managing/opt_out.asp)".

**Comment by archon810** [comment]
Thanks, I've fixed the link.
