### ISSUE TITLE
Aiolos

### ISSUE THREAD

**Issue by AiolosxTH** [android-police/apkmirror-public#198]
I can't find my APP APK on the website. APKMirror
But it says uploaded successfully when I re-upload it on the website.

**Comment by AiolosxTH** [comment]
![image](https://user-images.githubusercontent.com/95526369/144705790-ef896a3e-7a16-4ced-91ef-0acae07e3f28.png)
I can't find my APP APK on the website.
But it says uploaded successfully when I re-upload it on the website.

**Comment by AiolosxTH** [comment]
please check my apk or do i need it how much it cost
and how can i put my logo?

**Comment by AiolosxTH** [comment]
![image](https://user-images.githubusercontent.com/95526369/144705883-e6417786-fc4e-4af9-b4d0-aaf5a19e0da4.png)
I can't find it

**Comment by archon810** [comment]
This is not something we'll ever host on apkmirror.

**Comment by AiolosxTH** [comment]
ฉ้นต้องทำยังไง ถึงจะอัพโหลด apk ของฉัน ฉัน สามารถจ่ายเงินได้

ในวันที่ อา. 5 ธ.ค. 2021 00:43 น. Artem Russakovskii <
***@***.***> เขียนว่า:
