### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by 89z** [android-police/apkmirror-public#200]
Can you advise what process you are using to get the version history of an app? For example, you have many versions of this app:

https://www.apkmirror.com/apk/google-inc/youtube

How are you getting a list of the available versions? Does Google have an API for this? Or have you just been logging the version number for each new version?

**Comment by archon810** [comment]
I'm sorry, but we don't discuss internal site operations. This tracker is for bug reports and feature requests only.

**Comment by 89z** [comment]
https://github.com/facundoolano/google-play-scraper/issues/554

**Comment by 89z** [comment]
Its clear now that you are using open source software to run the site, at least in part.

In which case, you are bound by the MIT license to disclose the source code.
