### ISSUE TITLE
Search bar isn't working on the mobile website

### ISSUE THREAD

**Issue by junaidd09** [android-police/apkmirror-public#201]
#### Expected behavior
Search bar opens up on the mobile website.

#### Actual behavior
Website doesn't respond when search bar is clicked, even repeatedly.

#### Steps to reproduce the problem
Click the search bar.

**Comment by archon810** [comment]
It's working for me in Chrome stable 97 on Android. Can you please provide detailed reproduction steps?

**Comment by maciejmackowiak** [comment]
@junaidd09 are you using any ad blocker?
If you are and it is working with ad blocker disabled please open an issue in ad blocker issue tracker.
For example here is a github issue tracker for uBlock https://github.com/uBlockOrigin/uAssets/

**Comment by archon810** [comment]
Yeah, uBlock has been breaking the site while tweaking rules, they're being careless and don't seem to care.

**Comment by archon810** [comment]
Yeah, so uBlock broke it and didn't even care that they released an update with known issues https://github.com/uBlockOrigin/uAssets/issues/764#issuecomment-1010689113.

We worked around it, for now.

**Comment by junaidd09** [comment]
I was using it on Firefox. Ublock was the problem. I disabled it, refreshed the page and checked, then it worked. Then I reenabled ublock, refreshed the page and it worked. So I guess I just had to disable and re-enable ublock to fix the issue.

**Comment by archon810** [comment]
We made a site modification to fix the issue from our end, this is what you're seeing.

**Comment by junaidd09** [comment]
Thank you @archon810

**Comment by archon810** [comment]
uBlock maintainers keep half-assing the testing and constantly releasing faulty updates that break apkmirror. https://github.com/uBlockOrigin/uAssets/issues/11498

https://github.com/uBlockOrigin/uAssets/commit/2978920e3babc8deb5ba45736462599803f6d29f
