### ISSUE TITLE
Download link goes to the wrong APK

### ISSUE THREAD

**Issue by etoews** [android-police/apkmirror-public#37]
#### Expected behavior

Download link should take you to the NHL app.

#### Actual behavior

Download link takes you to Android Auto app instead.

#### Steps to reproduce the problem

1. Search for the NHL app: https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=nhl
1. Click on the Download arrow link for NHL 9.0.1 by BAMTECH LLC: https://www.apkmirror.com/apk/bamtech-llc-2/nhl-2/nhl-2-9-0-1-release/
1. You're redirect to the Android Auto app: https://www.apkmirror.com/apk/google-inc/android-auto/android-auto-1-0-1788739-release-release/android-auto-1-0-062923-1788739-release-android-apk-download/

**Comment by SeBsZ** [comment]
Thanks for your detailed report, I have fixed this issue.

**Comment by archon810** [comment]
The issue has been fixed in one of the past releases.
