### ISSUE TITLE
all your apks

### ISSUE THREAD

**Issue by frankflash9** [android-police/apkmirror-public#45]
#### Expected behavior
why do all your apk come up with 
app not installed 
the package conflicts with an existing package by the same name

why cant this be fixed 
galaxy tab s2 noughat

**Comment by archon810** [comment]
Any incompatibility between APK versions and your device are not supported on this bug tracker and are beyond its scope.

**Comment by diehard88** [comment]
brush it off... 
close issue....

that's it?

**Comment by archon810** [comment]
Yes, I can't help you with individual APK compatibility. We don't make those APKs.

**Comment by diehard88** [comment]
I understand.    Can you point us to the right direction?
The package conflict error is widespread and not isolated.
Samsung support is clueless and evasive.

thanks!
