### ISSUE TITLE
Check uploads against files already in pool but still not approved?

### ISSUE THREAD

**Issue by Rikk** [android-police/apkmirror-public#50]
Check uploads against files already uploaded before (in pool) but still not approved? I wonder why isn't it implemented yet? This would save time and bandwidth for both users and the server, right? (and disk space for the server, unless it doesn't save dups...)

**Comment by archon810** [comment]
The disk space is a non-issue because all the dupes are deleted upon publishing.

We currently don't show whether an APK was already uploaded but is in the queue for various reasons, and there are no current plans to change this.
