### ISSUE TITLE
Apkmirror remove post request

### ISSUE THREAD

**Issue by AxiK101** [android-police/apkmirror-public#52]
Duo to Amir's request, this upload:

https://www.apkmirror.com/apk/amirzaidi/rootless-pixel-launcher/rootless-pixel-launcher-3-2-release/rootless-pixel-launcher-3-2-android-apk-download/

must be removed from the site as it is an alpha build, not the final release. I apologize for uploading sooner than it should, please cosnider to remove it asap

Thanks

**Comment by archon810** [comment]
This has been dealt with.
