### ISSUE TITLE
Netflix APK version 5.15.0 build 26538 

### ISSUE THREAD

**Issue by TruJustice** [android-police/apkmirror-public#53]
#### Actual behavior
Hi there, 

Just a note that the Netflix APK workaround for the android box does bypass the new update (installed on March 11, 2018) which prevents the former Netflix app from working on the device.  However, there appears to be a minor glitch where the app does not allow one to scroll down through the various tv shows and movie categories in Netflix.

**Comment by archon810** [comment]
This forum is for issues with the website, not bugs or other issues with individual apps hosted. Please use the Disqus comment section on the site to discuss app issues.
