### ISSUE TITLE
[feature request] allow multiple choice for APK download

### ISSUE THREAD

**Issue by diehard88** [android-police/apkmirror-public#58]
Allow multiple APK to be selected for batch download.
Restrictions apply for the most obvious reasons.

 for instance: today's updates by Samsung. Batch limit of 5 apk files.

**Comment by archon810** [comment]
Sorry, batch downloads are not supported.

**Comment by diehard88** [comment]
Batch with 20 apk files?  No problem, click here

**Comment by diehard88** [comment]
@archon810 

thus the request...

:)

**Comment by diehard88** [comment]
@archon810 

LOL....  my request didn't last 30 seconds open.   Were you waiting for me?

:)

cheers!
