### ISSUE TITLE
oreo xor nougat

### ISSUE THREAD

**Issue by diehard88** [android-police/apkmirror-public#59]
guru meditation.

![](https://i.imgur.com/HDg5kt5.png)

![](https://i.imgur.com/GMzeZxx.jpg) 

the same paradox is found in other apps.

**Comment by archon810** [comment]
There is no wrong information. It's all automated, extracted from the APK. Feel free to examine the APK yourself, you'll see. Sometimes minapi > targetapi.

**Comment by archon810** [comment]
![image](https://user-images.githubusercontent.com/469543/38762341-b17eae7c-3f3f-11e8-982d-b606e0ef8881.png)

**Comment by diehard88** [comment]
wow!   thsnks man!
