### ISSUE TITLE
Problem parsing the package (Kindle Fire)

### ISSUE THREAD

**Issue by alansco** [android-police/apkmirror-public#61]
Installing Google Chrome on Kindle Fire - Android 4+ OS

Unable to install various versions... all result in "Problem parsing the package" error when trying to install downloads from your server...

#### Steps to reproduce the problem

https://www.apkmirror.com/apk/google-inc/chrome/chrome-63-0-3239-111-release/

**Comment by archon810** [comment]
This is not an issue with APK Mirror. The exact reason could be found in the Kindle Fire's logs, but if it's really running Android 4.0, as you can see all the Chrome APKs are at least 4.1+.
