### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by hanschke** [android-police/apkmirror-public#65]
download dont work for:

https://www.apkmirror.com/wp-content/uploads/2018/05/5b0ef8e16708c/com.android.vending_10.2.30-all_0_PR_198402259-81023000_minAPI16(armeabi,armeabi-v7a,mips,mips64,x86,x86_64)(240,320,480dpi)_apkmirror.com.apk?verify=1527708264-AphAjkX%2F%2FMrdtNISOlZvn4q%2BSx4SG7Ry26g1%2Fk4dIW0%3D

https://www.apkmirror.com/wp-content/uploads/2018/05/5b0ef66e62180/com.google.ar.core_1.2.180425134-180425134_minAPI24(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com.apk?verify=1527708387-HTAVAlkrtDSuG8MlDYZqY5NoET%2BxVsXzPf%2BYyTASUo8%3D

https://www.apkmirror.com/wp-content/uploads/2018/05/5b0eea7d2abb9/com.valvesoftware.android.steam.community_2.3.2-4537696_minAPI19(nodpi)_apkmirror.com.apk?verify=1527708358-%2B3B8e5KoHaMwEytuJ2ErSarZEZ7qTd%2FQKCKDDAr73xE%3D

**Comment by archon810** [comment]
Thanks, we're also seeing the issues, currently investigating.

**Comment by archon810** [comment]
We've identified the issue and fixed the permissions. I'm working on fixing the faulty code so it doesn't happen again.

**Comment by archon810** [comment]
Fix rolled out.
