### ISSUE TITLE
Problem with timer version 7.0.90.56

### ISSUE THREAD

**Issue by ValentineV3** [android-police/apkmirror-public#67]
#### Expected behavior
When phone is put on vibrate timer should automatically go on vibrate as well. Update 7.0.90.56 has eliminated this feature.

#### Actual behavior
When phone is put on vibrate the timer remains audiable. An extra menu must be accessed to force timer to go on vibrate. Having to access an extra menu to do this may be problematic when one uses the timer literally dozens of times every day, in various locations, both loud and quiet.

#### Recommended fix
Developer should add a setting to allow timer audiability to be dependant on phone audiability. One might want their timer to be automatically silenced when their phone is silenced so, for instance, their medication timer going off doesn't disturb other people at a performance.

**Comment by archon810** [comment]
Issues with individual apps is not what this tracker is for. Closing.

**Comment by ValentineV3** [comment]
Thanks for the help buddy.
