### ISSUE TITLE
Chrome (at least on Chrome OS) denies downloads from APK-Mirror

### ISSUE THREAD

**Issue by thommesborg** [android-police/apkmirror-public#68]
#### Steps to reproduce the problem: Try downloading any beta-app from APK-Mirror using Chrome OS v67

![image](https://user-images.githubusercontent.com/40795115/42218411-c5d6209e-7ec8-11e8-9809-3f1263af06b5.png)

**Comment by TPS** [comment]
Just to be completely clear:  _Any_ APK?  Have you tried something innocuous, but official, like [CrowdSource](https://www.apkmirror.com/apk/google-inc/crowdsource/)⁉️

**Comment by thommesborg** [comment]
Hi TPS, I thought Reddit might be innocuous. Thanks for the link and yes, that got downloaded.

![screenshot 2018-07-03 at 15 12 20](https://user-images.githubusercontent.com/40795115/42221852-d3842a00-7ed3-11e8-9130-97a9c20ad162.png)

**Comment by TPS** [comment]
So, maybe it's just Reddit? APK from https://www.apkmirror.com/apk/redditinc/reddit/?

**Comment by TPS** [comment]
No worries by me, I'm not official anyplace. 😀

Still, before you close this issue (as it seems ☐ly _outside_ the purview of APKMirror staff & really should be brought to attn of the ChromeOS devs), please edit the title & FP description for better detail & clarity.  Why cause unnecessary furor whenever this is indexed by a search engine & later found by someone else?

**Comment by archon810** [comment]
I've seen Chrome in general start asking this about apks downloaded not just from apkmirror.com lately. I don't believe it's anything to do with our site, or that we can do anything about it.

You can try filing a ticket in the Chrome bug tracker.

**Comment by thommesborg** [comment]
Hi Artem, I filed feedback via the Chrome/Chrome OS feedback-option. This goes directly to the dev's inbox. If needed I escalate it via Chromebook Central. 

Thanks for the feedback.
