### ISSUE TITLE
Non-Play Store Application - Clicking "Play Store" link brings user to "app not found" error page on Play Store

### ISSUE THREAD

**Issue by Justin12121** [android-police/apkmirror-public#69]
#### Expected behavior
The "Play Store" button should not appear if an application is not present on the Play Store.

#### Actual behavior
The button takes the user to the "error - app cannot be found" page on the Play Store.

#### Steps to reproduce the problem
https://www.apkmirror.com/apk/samsung-electronics-co-ltd/good-lock-2018/good-lock-2018-1-0-00-30-release/good-lock-2018-1-0-00-30-android-apk-download/

1. Click "View on Play Store" button.

**Comment by archon810** [comment]
We do not query the Play Store and show the button regardless because an app can show up at any point, especially if it's a new app, an app can show up for those who previously installed it but not others, an app can show up for beta testers but not others, an app can be geo limited, etc.
