### ISSUE TITLE
Apk upload engine

### ISSUE THREAD

**Issue by Kelvin15179** [android-police/apkmirror-public#70]
#### Expected behavior
Your upload apk engine should be able to distinguish the different variant of a same version of the app

#### Actual behavior
The engine regards the arm64 variant same as arm variant

#### Steps to reproduce the problem
Uploading the apk of the same version which has been uploaded by others in advance. Then the apk of the same version with other variant can't be uploaded.

**Comment by archon810** [comment]
This is a currently known recent issue. We'll have a fix out shortly.

Out of curiosity, what's the app in question?

**Comment by archon810** [comment]
The issue has been fixed.
