### ISSUE TITLE
App page out of date

### ISSUE THREAD

**Issue by orschiro** [android-police/apkmirror-public#71]
#### Expected behavior

I expected to find the latest version 4.2.365.439 of the ABC listen app on the [apk mirror](https://www.apkmirror.com/apk/australian-broadcasting-corporation/abc-radio/) page.

#### Actual behavior

But it only shows 4.0.331.358 from last year.

**Comment by TPS** [comment]
@orschiro If [it isn't submitted](https://www.apkmirror.com/apk-upload/), it's not going to be there.…  Why don't _you_⁉️

ProTip: [ML Manager](https://play.google.com/store/apps/details?id=com.javiersantos.mlmanager) makes doing so _really_ easy! :bow:

**Comment by orschiro** [comment]
Thanks! Now I understand the concept. I can submit it, yes. However, how do
I stay notified of new releases in the future?

**Comment by TPS** [comment]
There're several options right @ the top, just below [Description] [What's New].  I use PushBullet, myself.

**Comment by orschiro** [comment]
Let me roll back for a second to clarify.

I want to use this specific app called ABC Listen. However, it's only
available via the Play Store in Australia.

Hence, my thought was to subscribe to a RSS feed to be notified of new
releases for me to install the APK manually.

This is how I found APK Mirror. I would be glad in submitting new ABC
Listen releases to APK Mirror so that they appear in the RSS feed. But it
doesn't solve the initial issue of notifying me of new releases in the
first place.

Do you understand my issue?

**Comment by orschiro** [comment]
Appreciated, thanks!

Do you know of any way I can stay informed about new releases that I can
then upload to APK Mirror other than manually checking the Play Store for
new releases?

**Comment by TPS** [comment]
For _that_ case, [Yalp Store](https://www.apkmirror.com/apk/sergey-yeriomin/yalp-store/) WFM, but YMMV. 🤷

**Comment by orschiro** [comment]
Not sure what you mean by "WFM, but YMMV", but Yalp Store seems to be what
I am looking for.

Appreciate your help!
