### ISSUE TITLE
Error in html source of app's description causes glitch in the site

### ISSUE THREAD

**Issue by Rikk** [android-police/apkmirror-public#73]
The glitch: (bold text beyond the bounds of Description area)
>![glitch](https://user-images.githubusercontent.com/2916485/43832362-94ff4eba-9add-11e8-91ad-b123609fba0e.png)

The code in APKMirror:
>![source-apkmirror](https://user-images.githubusercontent.com/2916485/43832345-887519a4-9add-11e8-82a2-053dcfd67c85.png)

However, Play Store has correct code at this time:
>![source-playstore](https://user-images.githubusercontent.com/2916485/43832354-8f9b8600-9add-11e8-8023-ae05db9c930b.png)

Therefore, I think some fix in the site is needed to restrict this kind of mistake to its container.

**Comment by SeBsZ** [comment]
Thanks for your report. We do actually close unclosed tags, but in this case it conflicted with the < character a few lines earlier:
`For Android < 5.0, Dual SIM...` and decides to remove the </b>.

We'll let you know when this has been fixed. Thanks again.

**Comment by Rikk** [comment]
Oh I missed it... Then it is even easier, just encode that char. HTMLPurify would do it, but you don't use it on the site, right?

**Comment by archon810** [comment]
This issue is now fixed. Unfortunately, it wasn't nearly as easy as it seemed, but it's a good thing that it was pointed out and we (painfully) fixed it the right way.

**Comment by Rikk** [comment]
Yep, it could be dangerous, security wise...
