### ISSUE TITLE
No response is recieved after the apk file gets uploaded.

### ISSUE THREAD

**Issue by SArsalanK** [android-police/apkmirror-public#74]
No response is received after the APK file gets uploaded. The uploading pop up remains there. 
User should receive an email or by a popup message something like "Thanks you. Your apk file has been successfully submitted, we can take [your approx time to review] to review your app. We will reach back to you on the email you provided"

**Comment by archon810** [comment]
When the upload finishes on the site, you get a confirmation message for each apk. We are not going to add email support for new uploads - only for when apks are approved and go live.

**Comment by upintheairsheep** [comment]
> When the upload finishes on the site, you get a confirmation message in the upload modal for each apk. We are not going to add email support for new uploads - only for when apks are approved and go live.

Can you add a declining message?
