### ISSUE TITLE
Private message + Email on the Open Food Facts page

### ISSUE THREAD

**Issue by teolemon** [android-police/apkmirror-public#75]
#### Expected behavior
Empty notes, or "Initial publication"

#### Actual behavior
The notes for Open Food Facts include what I thought would be a private message. 
Is it possible to remove the message from the page ?

#### Steps to reproduce the problem
1. Go to https://www.apkmirror.com/apk/open-food-facts/open-food-facts-scan-food-get-the-nutriscore/open-food-facts-scan-food-get-the-nutriscore-2-8-7-release/open-food-facts-scan-food-get-the-nutriscore-2-8-7-android-apk-download/#notes
2. Spot the message, especially the motivations and my email I'd rather keep private :-)

**Comment by teolemon** [comment]
Perhaps making it clear in the submit form that the motivation will be public.

**Comment by archon810** [comment]
We'll consider adding a small clarification that notes will be public.

**Comment by archon810** [comment]
We've updated the upload form to make it more clear what will and will not be public.
