### ISSUE TITLE
Many app shows multiple times. 

### ISSUE THREAD

**Issue by mohmadsharifjamali** [android-police/apkmirror-public#80]
Example:
Here in https://www.apkmirror.com/apk/max-apps/

Max apps shows two versions of the same app..

#### Steps to reproduce the problem
Simply go to that URL, you'll see to like me. 
Please solve it, thanks..

**Comment by archon810** [comment]
These are 2 separate apps:
https://play.google.com/store/apps/details?id=com.opera.max.global
https://play.google.com/store/apps/details?id=com.opera.max.oem
