### ISSUE TITLE
App upload

### ISSUE THREAD

**Issue by ItsAnshu** [android-police/apkmirror-public#82]
I want to upload my own apk. 
So pls help me

**Comment by archon810** [comment]
You're free to upload, but it'll have to pass our curation process described here https://www.apkmirror.com/faq/#What_is_the_purpose_of_APKMirrorcom_What_APKs_are_accepted_I_just_uploaded_an_APK_but_it8217s_not_going_live. Uploads are not guaranteed to go live.
