### ISSUE TITLE
App upload.

### ISSUE THREAD

**Issue by ItsAnshu** [android-police/apkmirror-public#84]
Hi,
I want to upload an app with full description. So tell me the process so that i could enter all details self for my app. because when i m trying to upload my app through apk mirror then there is only option for file upload there in no option for details like description , app info etc. So please send me link to upload app if possible.

Regards 
Anshu

**Comment by archon810** [comment]
You can include the description in the notes, but if your app is on the Play Store, that's not necessary, we'll get those automatically.
