### ISSUE TITLE
[Feature Request] Ability to resubscribe to email notifications of uploaded APKs

### ISSUE THREAD

**Issue by Chan4077** [android-police/apkmirror-public#85]
#### Expected behavior

There should be an option to resubscribe to email notifications of uploaded APKs.

#### Actual behavior

There's currently no such support or any setting whatsoever.

#### Steps to reproduce the problem

1. Get an email notifying me that the APK I've uploaded has been successfully published.
2. Click on the unsubscribe link.
3. There's no way to resubscribe to such emails. This can be crucial as I want to be updated when the APK that I've uploaded has been successfully published to the site.

**Comment by archon810** [comment]
We have a TODO for this internally, but I have to admit it's pretty low priority. In the meantime, people who want to resubscribe can reach out to us via the Contact form.

**Comment by archon810** [comment]
This is now live.

**Comment by TPS** [comment]
Any details on how this is accessed, especially when using ML Manager for uploading?

**Comment by archon810** [comment]
The urls are at the bottom of the notification emails for when your uploads go live.

**Comment by TPS** [comment]
But the problem is not receiving those e-mail anymore, right?  So is there another method to resubscribe?

**Comment by archon810** [comment]
Just click the unsubscribe email from any previous notification, and you'll be able to resubscribe from there.

@SeBsZ For new emails, should we make it say "Unsubscribe or Resubscribe" to make it more clear?

**Comment by TPS** [comment]
If I haven't kept or can't find a previous notification e-mail?

**Comment by archon810** [comment]
Then you ask me here, I guess. Is this a hypothetical or?

**Comment by TPS** [comment]
Currently, but it's not inconceivable, right?

**Comment by archon810** [comment]
It is for anyone who unsubscribes by mistake and decides to go back because they'll still have the email.
