### ISSUE TITLE
Wear OS updates being pushed to Android OS

### ISSUE THREAD

**Issue by ETJAKEOC** [android-police/apkmirror-public#87]
#### Expected behavior
For the application to know whether or not the device it is running upon is a full fledge Android OS or a Wear OS alternative, and only show updates for said OS version.

#### Actual behavior
All updates, regardless of compatibility with the OS, are shown, have crashed multiple apps by accidentally installing the Wear OS only version on my Pixel 3, Gboard was a fun crash to come back from xD OTG adapter and a keyboard solved that

#### Steps to reproduce the problem
Search for updates to apps, go to install update (to Maps, for example), page you are redirected to is for Wear OS update since it is the latest version published, download APK and install it, your application will fail to run and force close consistently practically making your device useless unless you can uninstall it fast enough between taps, use PM uninstall, or go through file manager in TWRP

**Comment by archon810** [comment]
What application are we talking about here? Apkmirror doesn't have an official app.

**Comment by archon810** [comment]
Closing for lack of response.
