### ISSUE TITLE
Request: show version code too, and not just version name

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android-police/apkmirror-public#94]
I've noticed the website shows only the version name, but the real thing that matters is in fact the version code.
Developers can set whatever version name they want. It could even stay the same if they forgot.
But version code has to always increase, and it's an easy-to-read number. Not just some text.

**Comment by archon810** [comment]
The website does show version codes on apk pages, just not in titles.

**Comment by AndroidDeveloperLB** [comment]
Can you please add it? Maybe not in the title, but sub-title (description), just below the title, with smaller text font.
It's more important than version names. It's what really counts.
Also, it's incorrect that it's only in the titles. It's also on the APK pages.
Example:

Where do you see the version code here:

https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/sync-me-caller-id-block-4-18-3-release/#whatsnew

**Comment by archon810** [comment]
As I said, it shows it on apk pages, and the page you linked to is a release page. 

This is the corresponding apk page showing the version code https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/sync-me-caller-id-block-4-18-3-release/sync-me-caller-id-spam-call-blocker-contacts-4-18-3-android-apk-download/.

**Comment by AndroidDeveloperLB** [comment]
Please show it in the other web pages too.
Here are some possible places to put it:

![image](https://user-images.githubusercontent.com/5357526/60244487-2d71fb00-98c3-11e9-9f36-242551e7848e.png)

**Comment by archon810** [comment]
Version codes only make sense in the context of an apk, not a release because a release could have multiple apks, so the only location where a version code would even make sense in your screenshot is the list of apks at the bottom.

However, that would make the already limited in space table potentially a lot wider because some version codes are long. 

If you'd like to see the version code for an apk, you're welcome to visit the apk page.

**Comment by AndroidDeveloperLB** [comment]
Some points:

1. Actually, you can release 2 APK files in different times, and have the same version name for each, while having a different version code (because it's needed).
So you could, for example have this issue on the website:

"My app 1.2.3" - version code 123 , released on 2018
"My app 1.2.3" - version code 124, released on 2019

Users won't be able to differentiate between those.

2. Even if we ignore this, in some cases, app releases have only a single APK file, so it's incorrect to say that it's impossible. In those cases, the version code is ok to be shown anywhere.

3. As for space taken on the webpage, version names can be much longer than version codes. Version names are almost limitless. Version codes are not (an integer for most cases, and long in some rare cases).

4. But in any case, can you please show it here:

![image](https://user-images.githubusercontent.com/5357526/60245448-4b405f80-98c5-11e9-9d7a-493963e0da6a.png)

?

**Comment by archon810** [comment]
@SeBsZ Your input on these suggestions?

**Comment by archon810** [comment]
@SeBsZ Let's switch to showing the internal versioncode on release pages with single APKs.

**Comment by AndroidDeveloperLB** [comment]
I'm happy you consider this.

**Comment by SeBsZ** [comment]
@archon810 I created a PR for you to look at.

**Comment by archon810** [comment]
The PR is live.

**Comment by AndroidDeveloperLB** [comment]
Where do you see the version code?

**Comment by archon810** [comment]
In this comment, https://github.com/android-police/apkmirror-public/issues/94#issuecomment-506228174 - the version name here was replaced with the version code:
![image](https://user-images.githubusercontent.com/469543/76153421-a6e00100-6080-11ea-9d65-3fff9562a5c8.png)

**Comment by AndroidDeveloperLB** [comment]
I mean on main page of an app :
https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/

If I want to find a version number, I have to enter each of them...

**Comment by archon810** [comment]
As mentioned before, the app page only lists releases, not APKs. Releases don't have versioncodes.

**Comment by AndroidDeveloperLB** [comment]
Yes, so for the releases, I don't see version numbers. Not even one.
If you think there could be more, you could write multiple ones, or with "-".
With what you have added, it helps only when you already are deep inside, a moment before you download. This doesn't help in case I want to search a version number.
Look, even when I search, I don't see a version number:
https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=sync+me

**Comment by archon810** [comment]
Because again, those are releases, not APKs.

We're not going to put versioncodes from all APKs included in a release on a page listing just releases. This is 99.99% of the time unnecessary information on such pages which only clutters the UI, and there could be many variants in one release - Play Services has over 40 variants, for example.  https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=play+services.

**Comment by AndroidDeveloperLB** [comment]
OK here are notes why what you wrote is incorrect :

1. Releases always include APK files. Often a single one, which makes sense to show the version number too. But as I wrote, even if there are more than one, you can still group them one way or another, or avoid writing in this case. A possible grouping could be to min and max of them, and write "+X more".  In the example I've shown, all releases have a single APK. You can at least do when that's the case.

2. The version name, as I wrote, doesn't mean anything technically. Only the version code. You can install v321 on top v123 (update) but not the opposite, but technically it could happen that you can install "v1.2.3" on top of "v3.2.1" . Not only that, but version name can be just some string such as "testing some feature", which doesn't mean anything.

3. Clutter the UI - You have an arrow icon (download) that does exactly the same as clicking on the row. 
Why does it exist ?

4. Also, as I wrote, version name can be much longer than version number. Version number is limited to how long the variable is, and version name is a whole string. You can easily clutter the UI showing the whole version name. You have plenty of space
