### ISSUE TITLE
Request: offer API for Android via SDK

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android-police/apkmirror-public#95]
As the title says.

**Comment by archon810** [comment]
We do not have plans to offer a public API, sorry.

For private API needs, feel free to reach out to discuss the needs of your company or project.

**Comment by AndroidDeveloperLB** [comment]
That's too bad. May I ask why not? 
What about what's available as website URLs ? Do you plan to keep those ?
For example, searching of an app or a package name. Or reaching the exact app via package name.

**Comment by archon810** [comment]
There are already dozens of apkmirror.com clones and leeches that take our apks and information and don't give anything back in return. I have no interest in making it even easier for them to leech.

We serve our users who view ads in return for our hosting.

**Comment by AndroidDeveloperLB** [comment]
I see. 
Isn't it better to provide an official SDK then?  At least you could limit it somehow there (reduce server work, if that's what you mean by leeching), and have more control...
One of the terms of using it could be to have credit to the website, and to always be able to reach the website from the app that uses it.
As for me, I just wanted to add an option for the user to reach the website from my app, and I prefer not to assume that URLs are always used the same way.

**Comment by archon810** [comment]
Sorry, we are not going to make it easier for scrapers to get the data.

**Comment by AndroidDeveloperLB** [comment]
I see.
Can I assume URL structure? 
Meaning, for example:

searching for app "google calendar" :
https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=google+calendar

Searching for package name of app "com.google.android.calendar" :
https://www.apkmirror.com/?post_type=app_release&searchtype=app&s=com.google.android.calendar

?

**Comment by archon810** [comment]
Url structure can change and isn't guaranteed. Also, you may run into Cloudflare bot-blocking at some point.

**Comment by AndroidDeveloperLB** [comment]
I mean that it's for users. Not for server.
I don't even have a server (and I don't want to have one either).
