### ISSUE TITLE
Request: when there is only one APK available, go directly to its page

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android-police/apkmirror-public#96]
For example, instead of going to here:
https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/sync-me-caller-id-block-4-18-3-release/

-go directly to :
https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/sync-me-caller-id-block-4-18-3-release/sync-me-caller-id-spam-call-blocker-contacts-4-18-3-android-apk-download/

The reason is that there is actually only one choice, and it already shows all of the information on the previous page, and more.

**Comment by archon810** [comment]
Many times, only one apk is uploaded but more will get uploaded in the future. We want to preserve the release page in such a case and not redirect, even when only one apk is uploaded.

We only redirect right away when we know there haven't been APK requirement variations in the past.

**Comment by AndroidDeveloperLB** [comment]
@archon810 Right, but as long as it's not as such (meaning you have only one), there is no reason to show us a webpage that has only one option to go to.
It's better to go directly to it.

"We only redirect right away when we know there haven't been APK requirement variations in the past."

So why don't I see it on the case I've written? Go to any release here, and see that it shows a webpage with "show all available APKs", even though there is always just one available.

**Comment by archon810** [comment]
It's because this app has had variants present: https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/#variants.

**Comment by AndroidDeveloperLB** [comment]
The given link shows a huge difference between the versions and the dates .

And, it doesn't make sense that those versions will affect new ones. If I look at the newest version that I can find, I still see just one that I can download:

https://www.apkmirror.com/apk/sync-me/sync-me-caller-id-block/sync-me-caller-id-block-4-18-9-release/
