### ISSUE TITLE
An Issue with post, Play Store Link needs to be updated on your Featured Article

### ISSUE THREAD

**Issue by fineanmol** [android-police/apkmirror-public#98]
#### Expected behavior

Hey,
we have updated our application link on play store but on your featured article its, the old one and invalid now,
can you please update the link so your users don't get confused and doesn't report your article as an invalid link issue.
Post URL = 
https://www.apkmirror.com/apk/hora-apps/leafpic/

#### Actual behavior
New Updated Playstore Link is:
https://play.google.com/store/apps/details?id=org.nightowldevelopers.leafpic

#### Steps to reproduce the problem
New Article must be now:
LeafPic is a fluid, material-designed alternative gallery, it also is ad-free and open source under GPLv3 license. It doesn't miss any of the main features of a stock gallery, we also have in plan to add some useful feature,
suggestions are appreciated!

Design
LeafPic offers 50 main colors, 9 accent colors, and 3 base themes: light, dark and amoled black, all surrounded by an immersive user experience which means that there are over 1,800 theme combinations to customize the app as you prefer!

Management
You can easily manage your files with features like copy, move, rename and affix with very nice user experience and a beautiful design. There is also a lightweight photo editor able to crop and rotate images.

Privacy
We respect your privacy since the project is the open-source you can check what we do with your media.
You can hide folders ad access them with a password.

You can find the source code on GitHub on github.com/fineanmol/LeafPic
stay tuned!

**Comment by archon810** [comment]
What featured article are you talking about?

**Comment by archon810** [comment]
I've looked into this and here's what I have to say. Get out of here with your spam shit.

The original app is open source and development was abandoned https://gitlab.com/HoraApps/LeafPic/issues.

You cloned the repo, added ads, uploaded to the Play Store with horribly broken English in the description and changelog, and are now trying to pass this app as a new replacement for LeafPic https://github.com/fineanmol/LeafPic/commits/master.

No, we will not host your app.
